# Environments sensitive for application
# Database Secrets
[default]
DATABASE_NAME="root"
DATABASE_HOST="localhost"
DATABASE_PORT=3306
DATABASE_USER="root"
DATABASE_PASSWORD="root"
DATABASE_DIALECT_DRIVER="mysql+mysqlconnector"  # Example using dialect: "mysql+pymssql"