version: "3.7"

networks:
  subnet_gym:
    name: subnet_gym

services:
  api:
    container_name: "api_gym_time_clock"
    build: .
    env_file: .env
    volumes:
      - .:/app/src
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
    networks:
      - subnet_gym

  db:
    image: mysql:8
    container_name: "mysql_gym_time_clock"
    env_file: .env
    hostname: "${DATABASE_HOST}"
    ports:
      - "3306:3306"
    networks:
      - subnet_gym
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_DATABASE=${DATABASE_NAME}
