# This is a basic workflow to help you get started with Actions

name: Gym Time Clock CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    #----------------------------------------------
    #       check-out repo and set-up python
    #----------------------------------------------
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.4
      uses: actions/setup-python@v4
      with:
        python-version: "3.10.4"

    #----------------------------------------------
    #  -----  install & configure poetry  -----
    #----------------------------------------------
    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: false
        installer-parallel: true

    #----------------------------------------------
    #  -----  install and running pre-commit  -----
    #----------------------------------------------
    - name: Install pre-commit
      run: |
        pip install pre-commit && pip install setuptools


    - name: Run pre-commit
      run: |
        poetry run pre-commit run --all-files
